// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateID():Promise<string>;

export function GetAlwaysOnTop():Promise<boolean>;

export function LoadData():Promise<any>;

export function SaveData(arg1:any):Promise<void>;

export function SetAlwaysOnTop(arg1:boolean):Promise<void>;

export function WindowClose():Promise<void>;

export function WindowMinimise():Promise<void>;
