// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateID() {
  return window['go']['main']['App']['GenerateID']();
}

export function GetAlwaysOnTop() {
  return window['go']['main']['App']['GetAlwaysOnTop']();
}

export function LoadData() {
  return window['go']['main']['App']['LoadData']();
}

export function SaveData(arg1) {
  return window['go']['main']['App']['SaveData'](arg1);
}

export function SetAlwaysOnTop(arg1) {
  return window['go']['main']['App']['SetAlwaysOnTop'](arg1);
}

export function WindowClose() {
  return window['go']['main']['App']['WindowClose']();
}

export function WindowMinimise() {
  return window['go']['main']['App']['WindowMinimise']();
}
